
export const items = [
  
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 15",
    imgSrc: "https://www.maplestore.in/cdn/shop/files/iPhone_15_Blue_PDP_Image_Position-1__en-IN_9d151e10-d809-499c-95cd-5c7cb7ea9dbe.jpg?v=1701822313",
    amazonLink: "https://www.amazon.in/Apple-iPhone-15-128-GB/dp/B0CHX2F5QT/ref=sr_1_1_sspa?crid=2ALR6A0QR6100&keywords=iphone%2B15&qid=1702967350&sprefix=iphone%2B1%2Caps%2C288&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    description: "Apple iPhone 15 (128 GB) - Blue",
    price: "89999",
  },
  {
    id: 10,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: "89999",
  },
  {
    id: 5,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/71LRY1j6UHL._SY450_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Xiaomi Pad 6 - Dark Grey",
    price: "49999",
  },
  {
    id: 7,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/71ioKNHjXKL._SY450_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Xiaomi Pad 6 - Mist Blue",
    price: "29999",
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/31p5cVyRLmL._SY445_SX342_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 13 (128GB) - Pink",
    price: "79999",
  },
  {
    id: 6,
    category: "tablets",
    title: "Redmi Pad",
    imgSrc: "https://m.media-amazon.com/images/I/61EFdbc0nrL._SY450_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description: "Redmi Pad - Moonlight Silver",
    price: "19999",
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 12",
    imgSrc: "https://m.media-amazon.com/images/I/71hIfcIPyxS._SX679_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Purple",
    price: "69999",
  },
  {
    id: 4,
    category: "laptops",
    title: "Lenovo IdeaPad",
    imgSrc: "https://m.media-amazon.com/images/I/61PeZXpc5-L._SY450_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: 'Lenovo IdeaPad | Intel Core i5 12450H 14" (35.5cm) ',
    price: "29999",
  },
  {
    id: 9,
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description: "Samsung Galaxy Tab A8 2- Gray, (SM-X200NZAEINU)",
    price: "49999",
  },
  {
    id: 8,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description:
      "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ",
    price: "89999",
  },
  {
    id: 11,
    category: "headphones",
    title: "boAt Rockerz 450",
    imgSrc: "https://m.media-amazon.com/images/I/61u1VALn6JL._SY450_.jpg",
    amazonLink: "https://www.amazon.in/Boat-Rockerz-450-Lightweight-Compatibility/dp/B08667772G/ref=sr_1_4?crid=2F5I7G4J42JNT&keywords=headphones&qid=1702976615&sprefix=head%2Caps%2C270&sr=8-4&th=1",
    description:
      "boAt Rockerz 450-(Aqua Blue)",
    price: "89999",
  },

];
